package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Areas generated by hbm2java
 */
@Entity
@Table(name = "areas", catalog = "xboxlive_akdm")
public class Areas implements java.io.Serializable {

	private Integer areaId;
	private String areaTitle;

	public Areas() {
	}

	public Areas(String areaTitle) {
		this.areaTitle = areaTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "area_id", unique = true, nullable = false)
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	@Column(name = "area_title", nullable = false)
	public String getAreaTitle() {
		return this.areaTitle;
	}

	public void setAreaTitle(String areaTitle) {
		this.areaTitle = areaTitle;
	}

}
