package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendanceId generated by hbm2java
 */
@Embeddable
public class AttendanceId implements java.io.Serializable {

	private int attendanceId;
	private int userId;
	private int sabhaId;
	private int isAttended;

	public AttendanceId() {
	}

	public AttendanceId(int attendanceId, int userId, int sabhaId,
			int isAttended) {
		this.attendanceId = attendanceId;
		this.userId = userId;
		this.sabhaId = sabhaId;
		this.isAttended = isAttended;
	}

	@Column(name = "attendance_id", nullable = false)
	public int getAttendanceId() {
		return this.attendanceId;
	}

	public void setAttendanceId(int attendanceId) {
		this.attendanceId = attendanceId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "sabha_id", nullable = false)
	public int getSabhaId() {
		return this.sabhaId;
	}

	public void setSabhaId(int sabhaId) {
		this.sabhaId = sabhaId;
	}

	@Column(name = "is_attended", nullable = false)
	public int getIsAttended() {
		return this.isAttended;
	}

	public void setIsAttended(int isAttended) {
		this.isAttended = isAttended;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttendanceId))
			return false;
		AttendanceId castOther = (AttendanceId) other;

		return (this.getAttendanceId() == castOther.getAttendanceId())
				&& (this.getUserId() == castOther.getUserId())
				&& (this.getSabhaId() == castOther.getSabhaId())
				&& (this.getIsAttended() == castOther.getIsAttended());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getAttendanceId();
		result = 37 * result + this.getUserId();
		result = 37 * result + this.getSabhaId();
		result = 37 * result + this.getIsAttended();
		return result;
	}

}
