package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BloodGroups generated by hbm2java
 */
@Entity
@Table(name = "blood_groups", catalog = "xboxlive_akdm")
public class BloodGroups implements java.io.Serializable {

	private Integer bloodGroupId;
	private String bloodGroupTitle;

	public BloodGroups() {
	}

	public BloodGroups(String bloodGroupTitle) {
		this.bloodGroupTitle = bloodGroupTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "blood_group_id", unique = true, nullable = false)
	public Integer getBloodGroupId() {
		return this.bloodGroupId;
	}

	public void setBloodGroupId(Integer bloodGroupId) {
		this.bloodGroupId = bloodGroupId;
	}

	@Column(name = "blood_group_title", nullable = false, length = 20)
	public String getBloodGroupTitle() {
		return this.bloodGroupTitle;
	}

	public void setBloodGroupTitle(String bloodGroupTitle) {
		this.bloodGroupTitle = bloodGroupTitle;
	}

}
