package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Countries generated by hbm2java
 */
@Entity
@Table(name = "countries", catalog = "xboxlive_akdm")
public class Countries implements java.io.Serializable {

	private Integer countriesId;
	private String countriesName;
	private String countriesIsoCode;
	private String countriesIsdCode;

	public Countries() {
	}

	public Countries(String countriesName, String countriesIsoCode) {
		this.countriesName = countriesName;
		this.countriesIsoCode = countriesIsoCode;
	}

	public Countries(String countriesName, String countriesIsoCode,
			String countriesIsdCode) {
		this.countriesName = countriesName;
		this.countriesIsoCode = countriesIsoCode;
		this.countriesIsdCode = countriesIsdCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "countries_id", unique = true, nullable = false)
	public Integer getCountriesId() {
		return this.countriesId;
	}

	public void setCountriesId(Integer countriesId) {
		this.countriesId = countriesId;
	}

	@Column(name = "countries_name", nullable = false, length = 64)
	public String getCountriesName() {
		return this.countriesName;
	}

	public void setCountriesName(String countriesName) {
		this.countriesName = countriesName;
	}

	@Column(name = "countries_iso_code", nullable = false, length = 2)
	public String getCountriesIsoCode() {
		return this.countriesIsoCode;
	}

	public void setCountriesIsoCode(String countriesIsoCode) {
		this.countriesIsoCode = countriesIsoCode;
	}

	@Column(name = "countries_isd_code", length = 7)
	public String getCountriesIsdCode() {
		return this.countriesIsdCode;
	}

	public void setCountriesIsdCode(String countriesIsdCode) {
		this.countriesIsdCode = countriesIsdCode;
	}

}
