package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mandals generated by hbm2java
 */
@Entity
@Table(name = "mandals", catalog = "xboxlive_akdm")
public class Mandals implements java.io.Serializable {

	private Integer mandalId;
	private String mandalTitle;

	public Mandals() {
	}

	public Mandals(String mandalTitle) {
		this.mandalTitle = mandalTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mandal_id", unique = true, nullable = false)
	public Integer getMandalId() {
		return this.mandalId;
	}

	public void setMandalId(Integer mandalId) {
		this.mandalId = mandalId;
	}

	@Column(name = "mandal_title", nullable = false)
	public String getMandalTitle() {
		return this.mandalTitle;
	}

	public void setMandalTitle(String mandalTitle) {
		this.mandalTitle = mandalTitle;
	}

}
