package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MyguestsId generated by hbm2java
 */
@Embeddable
public class MyguestsId implements java.io.Serializable {

	private int id;
	private String firstname;
	private String lastname;
	private String email;
	private Date regDate;

	public MyguestsId() {
	}

	public MyguestsId(int id, String firstname, String lastname, Date regDate) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.regDate = regDate;
	}

	public MyguestsId(int id, String firstname, String lastname, String email,
			Date regDate) {
		this.id = id;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.regDate = regDate;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MyguestsId))
			return false;
		MyguestsId castOther = (MyguestsId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getFirstname() == castOther.getFirstname()) || (this
						.getFirstname() != null
						&& castOther.getFirstname() != null && this
						.getFirstname().equals(castOther.getFirstname())))
				&& ((this.getLastname() == castOther.getLastname()) || (this
						.getLastname() != null
						&& castOther.getLastname() != null && this
						.getLastname().equals(castOther.getLastname())))
				&& ((this.getEmail() == castOther.getEmail()) || (this
						.getEmail() != null && castOther.getEmail() != null && this
						.getEmail().equals(castOther.getEmail())))
				&& ((this.getRegDate() == castOther.getRegDate()) || (this
						.getRegDate() != null && castOther.getRegDate() != null && this
						.getRegDate().equals(castOther.getRegDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getFirstname() == null ? 0 : this.getFirstname().hashCode());
		result = 37 * result
				+ (getLastname() == null ? 0 : this.getLastname().hashCode());
		result = 37 * result
				+ (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result
				+ (getRegDate() == null ? 0 : this.getRegDate().hashCode());
		return result;
	}

}
