package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PushNotification generated by hbm2java
 */
@Entity
@Table(name = "push_notification", catalog = "xboxlive_akdm")
public class PushNotification implements java.io.Serializable {

	private Integer id;
	private int messageId;
	private String fromUserId;
	private String toUserId;
	private String message;
	private String privateModeEndTime;
	private String isRead;
	private String thumbImageUrl;
	private String latestMessageId;
	private String opponentDisplayName;
	private String isDeleted;
	private String thumbVideoUrl;
	private String messageType;
	private String editedImageUrl;
	private String isPrivateModeOn;
	private String privateModeTime;
	private String originalImageUrl;
	private String videoUrl;
	private String messageTime;

	public PushNotification() {
	}

	public PushNotification(int messageId, String fromUserId, String toUserId,
			String message, String privateModeEndTime, String isRead,
			String thumbImageUrl, String latestMessageId,
			String opponentDisplayName, String isDeleted, String thumbVideoUrl,
			String messageType, String editedImageUrl, String isPrivateModeOn,
			String privateModeTime, String originalImageUrl, String videoUrl,
			String messageTime) {
		this.messageId = messageId;
		this.fromUserId = fromUserId;
		this.toUserId = toUserId;
		this.message = message;
		this.privateModeEndTime = privateModeEndTime;
		this.isRead = isRead;
		this.thumbImageUrl = thumbImageUrl;
		this.latestMessageId = latestMessageId;
		this.opponentDisplayName = opponentDisplayName;
		this.isDeleted = isDeleted;
		this.thumbVideoUrl = thumbVideoUrl;
		this.messageType = messageType;
		this.editedImageUrl = editedImageUrl;
		this.isPrivateModeOn = isPrivateModeOn;
		this.privateModeTime = privateModeTime;
		this.originalImageUrl = originalImageUrl;
		this.videoUrl = videoUrl;
		this.messageTime = messageTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "message_id", nullable = false)
	public int getMessageId() {
		return this.messageId;
	}

	public void setMessageId(int messageId) {
		this.messageId = messageId;
	}

	@Column(name = "from_user_id", nullable = false, length = 65535)
	public String getFromUserId() {
		return this.fromUserId;
	}

	public void setFromUserId(String fromUserId) {
		this.fromUserId = fromUserId;
	}

	@Column(name = "to_user_id", nullable = false, length = 65535)
	public String getToUserId() {
		return this.toUserId;
	}

	public void setToUserId(String toUserId) {
		this.toUserId = toUserId;
	}

	@Column(name = "message", nullable = false, length = 65535)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "private_mode_endTime", nullable = false, length = 65535)
	public String getPrivateModeEndTime() {
		return this.privateModeEndTime;
	}

	public void setPrivateModeEndTime(String privateModeEndTime) {
		this.privateModeEndTime = privateModeEndTime;
	}

	@Column(name = "is_read", nullable = false, length = 65535)
	public String getIsRead() {
		return this.isRead;
	}

	public void setIsRead(String isRead) {
		this.isRead = isRead;
	}

	@Column(name = "thumb_image_url", nullable = false, length = 65535)
	public String getThumbImageUrl() {
		return this.thumbImageUrl;
	}

	public void setThumbImageUrl(String thumbImageUrl) {
		this.thumbImageUrl = thumbImageUrl;
	}

	@Column(name = "latest_message_id", nullable = false, length = 65535)
	public String getLatestMessageId() {
		return this.latestMessageId;
	}

	public void setLatestMessageId(String latestMessageId) {
		this.latestMessageId = latestMessageId;
	}

	@Column(name = "opponent_display_name", nullable = false, length = 65535)
	public String getOpponentDisplayName() {
		return this.opponentDisplayName;
	}

	public void setOpponentDisplayName(String opponentDisplayName) {
		this.opponentDisplayName = opponentDisplayName;
	}

	@Column(name = "is_deleted", nullable = false, length = 65535)
	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "thumb_video_url", nullable = false, length = 65535)
	public String getThumbVideoUrl() {
		return this.thumbVideoUrl;
	}

	public void setThumbVideoUrl(String thumbVideoUrl) {
		this.thumbVideoUrl = thumbVideoUrl;
	}

	@Column(name = "message_type", nullable = false, length = 65535)
	public String getMessageType() {
		return this.messageType;
	}

	public void setMessageType(String messageType) {
		this.messageType = messageType;
	}

	@Column(name = "edited_image_url", nullable = false, length = 65535)
	public String getEditedImageUrl() {
		return this.editedImageUrl;
	}

	public void setEditedImageUrl(String editedImageUrl) {
		this.editedImageUrl = editedImageUrl;
	}

	@Column(name = "is_private_mode_on", nullable = false, length = 65535)
	public String getIsPrivateModeOn() {
		return this.isPrivateModeOn;
	}

	public void setIsPrivateModeOn(String isPrivateModeOn) {
		this.isPrivateModeOn = isPrivateModeOn;
	}

	@Column(name = "private_mode_time", nullable = false, length = 65535)
	public String getPrivateModeTime() {
		return this.privateModeTime;
	}

	public void setPrivateModeTime(String privateModeTime) {
		this.privateModeTime = privateModeTime;
	}

	@Column(name = "original_image_url", nullable = false, length = 65535)
	public String getOriginalImageUrl() {
		return this.originalImageUrl;
	}

	public void setOriginalImageUrl(String originalImageUrl) {
		this.originalImageUrl = originalImageUrl;
	}

	@Column(name = "video_url", nullable = false, length = 65535)
	public String getVideoUrl() {
		return this.videoUrl;
	}

	public void setVideoUrl(String videoUrl) {
		this.videoUrl = videoUrl;
	}

	@Column(name = "message_time", nullable = false, length = 65535)
	public String getMessageTime() {
		return this.messageTime;
	}

	public void setMessageTime(String messageTime) {
		this.messageTime = messageTime;
	}

}
