package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sabhas generated by hbm2java
 */
@Entity
@Table(name = "sabhas", catalog = "xboxlive_akdm")
public class Sabhas implements java.io.Serializable {

	private Integer sabhaId;
	private String sabhaTitle;
	private int mandalId;
	private Date date;
	private Date startTime;
	private Date endTime;
	private int status;
	private int createdDate;
	private int updatedDate;

	public Sabhas() {
	}

	public Sabhas(String sabhaTitle, int mandalId, Date date, Date startTime,
			Date endTime, int status, int createdDate, int updatedDate) {
		this.sabhaTitle = sabhaTitle;
		this.mandalId = mandalId;
		this.date = date;
		this.startTime = startTime;
		this.endTime = endTime;
		this.status = status;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sabha_id", unique = true, nullable = false)
	public Integer getSabhaId() {
		return this.sabhaId;
	}

	public void setSabhaId(Integer sabhaId) {
		this.sabhaId = sabhaId;
	}

	@Column(name = "sabha_title", nullable = false)
	public String getSabhaTitle() {
		return this.sabhaTitle;
	}

	public void setSabhaTitle(String sabhaTitle) {
		this.sabhaTitle = sabhaTitle;
	}

	@Column(name = "mandal_id", nullable = false)
	public int getMandalId() {
		return this.mandalId;
	}

	public void setMandalId(int mandalId) {
		this.mandalId = mandalId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", nullable = false, length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", nullable = false, length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "created_date", nullable = false)
	public int getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(int createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_date", nullable = false)
	public int getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(int updatedDate) {
		this.updatedDate = updatedDate;
	}

}
