package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills", catalog = "xboxlive_akdm")
public class Skills implements java.io.Serializable {

	private Integer skillId;
	private String skillTitle;

	public Skills() {
	}

	public Skills(String skillTitle) {
		this.skillTitle = skillTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "skill_id", unique = true, nullable = false)
	public Integer getSkillId() {
		return this.skillId;
	}

	public void setSkillId(Integer skillId) {
		this.skillId = skillId;
	}

	@Column(name = "skill_title", nullable = false)
	public String getSkillTitle() {
		return this.skillTitle;
	}

	public void setSkillTitle(String skillTitle) {
		this.skillTitle = skillTitle;
	}

}
