package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ssp generated by hbm2java
 */
@Entity
@Table(name = "ssp", catalog = "xboxlive_akdm")
public class Ssp implements java.io.Serializable {

	private Integer sspId;
	private String sspTitle;

	public Ssp() {
	}

	public Ssp(String sspTitle) {
		this.sspTitle = sspTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ssp_id", unique = true, nullable = false)
	public Integer getSspId() {
		return this.sspId;
	}

	public void setSspId(Integer sspId) {
		this.sspId = sspId;
	}

	@Column(name = "ssp_title", nullable = false)
	public String getSspTitle() {
		return this.sspTitle;
	}

	public void setSspTitle(String sspTitle) {
		this.sspTitle = sspTitle;
	}

}
