package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Study generated by hbm2java
 */
@Entity
@Table(name = "study", catalog = "xboxlive_akdm")
public class Study implements java.io.Serializable {

	private Integer studyId;
	private String studyTitle;

	public Study() {
	}

	public Study(String studyTitle) {
		this.studyTitle = studyTitle;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "study_id", unique = true, nullable = false)
	public Integer getStudyId() {
		return this.studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}

	@Column(name = "study_title", nullable = false)
	public String getStudyTitle() {
		return this.studyTitle;
	}

	public void setStudyTitle(String studyTitle) {
		this.studyTitle = studyTitle;
	}

}
