package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserRules generated by hbm2java
 */
@Entity
@Table(name = "user_rules", catalog = "xboxlive_akdm")
public class UserRules implements java.io.Serializable {

	private Integer id;
	private UserRoles userRoles;
	private String privilegesController;
	private String privilegesActions;
	private String permission;
	private String permissionType;
	private Set userRulesMenus = new HashSet(0);

	public UserRules() {
	}

	public UserRules(UserRoles userRoles, String privilegesController,
			String privilegesActions, String permission) {
		this.userRoles = userRoles;
		this.privilegesController = privilegesController;
		this.privilegesActions = privilegesActions;
		this.permission = permission;
	}

	public UserRules(UserRoles userRoles, String privilegesController,
			String privilegesActions, String permission, String permissionType,
			Set userRulesMenus) {
		this.userRoles = userRoles;
		this.privilegesController = privilegesController;
		this.privilegesActions = privilegesActions;
		this.permission = permission;
		this.permissionType = permissionType;
		this.userRulesMenus = userRulesMenus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false)
	public UserRoles getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(UserRoles userRoles) {
		this.userRoles = userRoles;
	}

	@Column(name = "privileges_controller", nullable = false)
	public String getPrivilegesController() {
		return this.privilegesController;
	}

	public void setPrivilegesController(String privilegesController) {
		this.privilegesController = privilegesController;
	}

	@Column(name = "privileges_actions", nullable = false, length = 65535)
	public String getPrivilegesActions() {
		return this.privilegesActions;
	}

	public void setPrivilegesActions(String privilegesActions) {
		this.privilegesActions = privilegesActions;
	}

	@Column(name = "permission", nullable = false, length = 6)
	public String getPermission() {
		return this.permission;
	}

	public void setPermission(String permission) {
		this.permission = permission;
	}

	@Column(name = "permission_type")
	public String getPermissionType() {
		return this.permissionType;
	}

	public void setPermissionType(String permissionType) {
		this.permissionType = permissionType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRules")
	public Set getUserRulesMenus() {
		return this.userRulesMenus;
	}

	public void setUserRulesMenus(Set userRulesMenus) {
		this.userRulesMenus = userRulesMenus;
	}

}
