package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Userstatus generated by hbm2java
 */
@Entity
@Table(name = "userstatus", catalog = "xboxlive_akdm")
public class Userstatus implements java.io.Serializable {

	private UserstatusId id;
	private byte online;
	private String presence;
	private String lastIpAddress;
	private String lastLoginDate;
	private String lastLogoffDate;

	public Userstatus() {
	}

	public Userstatus(UserstatusId id, byte online, String lastIpAddress,
			String lastLoginDate) {
		this.id = id;
		this.online = online;
		this.lastIpAddress = lastIpAddress;
		this.lastLoginDate = lastLoginDate;
	}

	public Userstatus(UserstatusId id, byte online, String presence,
			String lastIpAddress, String lastLoginDate, String lastLogoffDate) {
		this.id = id;
		this.online = online;
		this.presence = presence;
		this.lastIpAddress = lastIpAddress;
		this.lastLoginDate = lastLoginDate;
		this.lastLogoffDate = lastLogoffDate;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 64)),
			@AttributeOverride(name = "resource", column = @Column(name = "resource", nullable = false, length = 64)) })
	public UserstatusId getId() {
		return this.id;
	}

	public void setId(UserstatusId id) {
		this.id = id;
	}

	@Column(name = "online", nullable = false)
	public byte getOnline() {
		return this.online;
	}

	public void setOnline(byte online) {
		this.online = online;
	}

	@Column(name = "presence", length = 15)
	public String getPresence() {
		return this.presence;
	}

	public void setPresence(String presence) {
		this.presence = presence;
	}

	@Column(name = "lastIpAddress", nullable = false, length = 15)
	public String getLastIpAddress() {
		return this.lastIpAddress;
	}

	public void setLastIpAddress(String lastIpAddress) {
		this.lastIpAddress = lastIpAddress;
	}

	@Column(name = "lastLoginDate", nullable = false, length = 15)
	public String getLastLoginDate() {
		return this.lastLoginDate;
	}

	public void setLastLoginDate(String lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	@Column(name = "lastLogoffDate", length = 15)
	public String getLastLogoffDate() {
		return this.lastLogoffDate;
	}

	public void setLastLogoffDate(String lastLogoffDate) {
		this.lastLogoffDate = lastLogoffDate;
	}

}
