package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPermission generated by hbm2java
 */
@Entity
@Table(name = "user_permission", catalog = "xboxlive_akdm")
public class UserPermission implements java.io.Serializable {

	private Long id;
	private long userId;
	private long categoryId;
	private boolean canSeeLocation;
	private boolean canSeeRelationship;
	private boolean canSeeDateOfBirth;
	private long postHistoryDays;
	private Date createdAt;
	private Date updatedAt;

	public UserPermission() {
	}

	public UserPermission(long userId, long categoryId, boolean canSeeLocation,
			boolean canSeeRelationship, boolean canSeeDateOfBirth,
			long postHistoryDays, Date createdAt, Date updatedAt) {
		this.userId = userId;
		this.categoryId = categoryId;
		this.canSeeLocation = canSeeLocation;
		this.canSeeRelationship = canSeeRelationship;
		this.canSeeDateOfBirth = canSeeDateOfBirth;
		this.postHistoryDays = postHistoryDays;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "category_id", nullable = false)
	public long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(long categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "can_see_location", nullable = false)
	public boolean isCanSeeLocation() {
		return this.canSeeLocation;
	}

	public void setCanSeeLocation(boolean canSeeLocation) {
		this.canSeeLocation = canSeeLocation;
	}

	@Column(name = "can_see_relationship", nullable = false)
	public boolean isCanSeeRelationship() {
		return this.canSeeRelationship;
	}

	public void setCanSeeRelationship(boolean canSeeRelationship) {
		this.canSeeRelationship = canSeeRelationship;
	}

	@Column(name = "can_see_date_of_birth", nullable = false)
	public boolean isCanSeeDateOfBirth() {
		return this.canSeeDateOfBirth;
	}

	public void setCanSeeDateOfBirth(boolean canSeeDateOfBirth) {
		this.canSeeDateOfBirth = canSeeDateOfBirth;
	}

	@Column(name = "post_history_days", nullable = false)
	public long getPostHistoryDays() {
		return this.postHistoryDays;
	}

	public void setPostHistoryDays(long postHistoryDays) {
		this.postHistoryDays = postHistoryDays;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
