package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UserRulesMenu generated by hbm2java
 */
@Entity
@Table(name = "user_rules_menu", catalog = "xboxlive_akdm")
public class UserRulesMenu implements java.io.Serializable {

	private Integer id;
	private UserRules userRules;
	private String category;
	private int parentId;
	private String label;
	private String class_;
	private String url;
	private int position;
	private byte status;

	public UserRulesMenu() {
	}

	public UserRulesMenu(UserRules userRules, String category, int parentId,
			String label, String url, int position, byte status) {
		this.userRules = userRules;
		this.category = category;
		this.parentId = parentId;
		this.label = label;
		this.url = url;
		this.position = position;
		this.status = status;
	}

	public UserRulesMenu(UserRules userRules, String category, int parentId,
			String label, String class_, String url, int position, byte status) {
		this.userRules = userRules;
		this.category = category;
		this.parentId = parentId;
		this.label = label;
		this.class_ = class_;
		this.url = url;
		this.position = position;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_rules_id", nullable = false)
	public UserRules getUserRules() {
		return this.userRules;
	}

	public void setUserRules(UserRules userRules) {
		this.userRules = userRules;
	}

	@Column(name = "category", nullable = false, length = 12)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "parent_id", nullable = false)
	public int getParentId() {
		return this.parentId;
	}

	public void setParentId(int parentId) {
		this.parentId = parentId;
	}

	@Column(name = "label", nullable = false)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "class")
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "position", nullable = false)
	public int getPosition() {
		return this.position;
	}

	public void setPosition(int position) {
		this.position = position;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

}
