package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserSatsangDetails generated by hbm2java
 */
@Entity
@Table(name = "user_satsang_details", catalog = "xboxlive_akdm")
public class UserSatsangDetails implements java.io.Serializable {

	private Integer userSatsangDetailId;
	private int userId;
	private boolean aarti;
	private boolean puja;
	private boolean tilak;
	private boolean ekadasi;
	private boolean vachnamrut;
	private boolean swaminivato;
	private String otherreading;
	private int sspId;
	private boolean garshabha;
	private boolean dharmado;

	public UserSatsangDetails() {
	}

	public UserSatsangDetails(int userId, boolean aarti, boolean puja,
			boolean tilak, boolean ekadasi, boolean vachnamrut,
			boolean swaminivato, String otherreading, int sspId,
			boolean garshabha, boolean dharmado) {
		this.userId = userId;
		this.aarti = aarti;
		this.puja = puja;
		this.tilak = tilak;
		this.ekadasi = ekadasi;
		this.vachnamrut = vachnamrut;
		this.swaminivato = swaminivato;
		this.otherreading = otherreading;
		this.sspId = sspId;
		this.garshabha = garshabha;
		this.dharmado = dharmado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_satsang_detail_id", unique = true, nullable = false)
	public Integer getUserSatsangDetailId() {
		return this.userSatsangDetailId;
	}

	public void setUserSatsangDetailId(Integer userSatsangDetailId) {
		this.userSatsangDetailId = userSatsangDetailId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "aarti", nullable = false)
	public boolean isAarti() {
		return this.aarti;
	}

	public void setAarti(boolean aarti) {
		this.aarti = aarti;
	}

	@Column(name = "puja", nullable = false)
	public boolean isPuja() {
		return this.puja;
	}

	public void setPuja(boolean puja) {
		this.puja = puja;
	}

	@Column(name = "tilak", nullable = false)
	public boolean isTilak() {
		return this.tilak;
	}

	public void setTilak(boolean tilak) {
		this.tilak = tilak;
	}

	@Column(name = "ekadasi", nullable = false)
	public boolean isEkadasi() {
		return this.ekadasi;
	}

	public void setEkadasi(boolean ekadasi) {
		this.ekadasi = ekadasi;
	}

	@Column(name = "vachnamrut", nullable = false)
	public boolean isVachnamrut() {
		return this.vachnamrut;
	}

	public void setVachnamrut(boolean vachnamrut) {
		this.vachnamrut = vachnamrut;
	}

	@Column(name = "swaminivato", nullable = false)
	public boolean isSwaminivato() {
		return this.swaminivato;
	}

	public void setSwaminivato(boolean swaminivato) {
		this.swaminivato = swaminivato;
	}

	@Column(name = "otherreading", nullable = false)
	public String getOtherreading() {
		return this.otherreading;
	}

	public void setOtherreading(String otherreading) {
		this.otherreading = otherreading;
	}

	@Column(name = "ssp_id", nullable = false)
	public int getSspId() {
		return this.sspId;
	}

	public void setSspId(int sspId) {
		this.sspId = sspId;
	}

	@Column(name = "garshabha", nullable = false)
	public boolean isGarshabha() {
		return this.garshabha;
	}

	public void setGarshabha(boolean garshabha) {
		this.garshabha = garshabha;
	}

	@Column(name = "dharmado", nullable = false)
	public boolean isDharmado() {
		return this.dharmado;
	}

	public void setDharmado(boolean dharmado) {
		this.dharmado = dharmado;
	}

}
