package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserNormalDetails generated by hbm2java
 */
@Entity
@Table(name = "user_normal_details", catalog = "xboxlive_akdm")
public class UserNormalDetails implements java.io.Serializable {

	private Integer userNormalDetailId;
	private int userId;
	private int studyId;
	private int occupation;
	private String notes;
	private int bloodGroupId;

	public UserNormalDetails() {
	}

	public UserNormalDetails(int userId, int studyId, int occupation,
			String notes, int bloodGroupId) {
		this.userId = userId;
		this.studyId = studyId;
		this.occupation = occupation;
		this.notes = notes;
		this.bloodGroupId = bloodGroupId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "user_normal_detail_id", unique = true, nullable = false)
	public Integer getUserNormalDetailId() {
		return this.userNormalDetailId;
	}

	public void setUserNormalDetailId(Integer userNormalDetailId) {
		this.userNormalDetailId = userNormalDetailId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "study_id", nullable = false)
	public int getStudyId() {
		return this.studyId;
	}

	public void setStudyId(int studyId) {
		this.studyId = studyId;
	}

	@Column(name = "occupation", nullable = false)
	public int getOccupation() {
		return this.occupation;
	}

	public void setOccupation(int occupation) {
		this.occupation = occupation;
	}

	@Column(name = "notes", nullable = false, length = 65535)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "blood_group_id", nullable = false)
	public int getBloodGroupId() {
		return this.bloodGroupId;
	}

	public void setBloodGroupId(int bloodGroupId) {
		this.bloodGroupId = bloodGroupId;
	}

}
