package com.test.ws.entities;

// Generated Jan 1, 2018 2:31:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserstatusId generated by hbm2java
 */
@Embeddable
public class UserstatusId implements java.io.Serializable {

	private String username;
	private String resource;

	public UserstatusId() {
	}

	public UserstatusId(String username, String resource) {
		this.username = username;
		this.resource = resource;
	}

	@Column(name = "username", nullable = false, length = 64)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "resource", nullable = false, length = 64)
	public String getResource() {
		return this.resource;
	}

	public void setResource(String resource) {
		this.resource = resource;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserstatusId))
			return false;
		UserstatusId castOther = (UserstatusId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this
				.getUsername() != null && castOther.getUsername() != null && this
				.getUsername().equals(castOther.getUsername())))
				&& ((this.getResource() == castOther.getResource()) || (this
						.getResource() != null
						&& castOther.getResource() != null && this
						.getResource().equals(castOther.getResource())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result
				+ (getResource() == null ? 0 : this.getResource().hashCode());
		return result;
	}

}
